name: Publish Docker image
on: workflow_dispatch

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_PASSWORD }}
          password: ${{ secrets.DDOCKERHUB_USERNAME }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: your_dockerhub_username/your_image_name:latest, your_dockerhub_username/your_image_name:${{ github.ref_name }}